export const FETCH_AIRPORTS_REQUEST = "FETCH_AIRPORTS_REQUEST";
export const FETCH_AIRPORTS_SUCCES = "FETCH_AIRPORTS_SUCCES";

export const FETCH_FLIGHT_OFFERS_REQUEST = "FETCH_FLIGHT_OFFERS_REQUEST";
export const FETCH_FLIGHT_OFFERS_SUCCES = "FETCH_FLIGHT_OFFERS_SUCCES";

export const ADJUST_FROM = "ADDJUST_FROM";
export const ADJUST_MIN_TRAVELTIME = "ADJUST_MIN_TRAVELTIME";
export const ADJUST_MAX_TRAVELTIME = "ADJUST_MAX_TRAVELTIME";
export const ADJUST_START_PERIOD = "ADJUST_START_PERIOD";
export const ADJUST_END_PERIOD = "ADJUST_END_PERIOD";
export const ADJUST_OVERNIGHT_STAYS = "ADJUST_OVERNIGHT_STAYS";

export const GET_FINAL_FLIGHT_OFFERS = "GET_FINAL_FLIGHT_OFFERS";
