export const FETCH_AIRPORTS_REQUEST = "FETCH_AIRPORTS_REQUEST";
export const FETCH_AIRPORTS_SUCCES = "FETCH_AIRPORTS_SUCCES";

export const ADJUST_FROM = "ADDJUST_FROM";
export const ADJUST_MIN_TRAVELTIME = "ADJUST_MIN_TRAVELTIME";
export const ADJUST_MAX_TRAVELTIME = "ADJUST_MAX_TRAVELTIME";
export const ADJUST_START_PERIOD = "ADJUST_START_PERIOD";
export const ADJUST_END_PERIOD = "ADJUST_END_PERIOD";
export const ADJUST_OVERNIGHT_STAY = "ADJUST_OVERNIGHT_STAY";
